### ISSUE TITLE
[FEATURE] 회원은 회원 정보를 조회할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#106]
### ✨ Describe
- [ ] 회원 도메인은 다음 회원 정보를 가지고 있다.
- [ ] 회원 도메인에서 회원 정보를 조회할 수 있다.

### 회원 정보
| 속성 | 설명 | 조회 권한 | 
| -- | -- | -- | 
| id | 사용자 식별값 | ALL | 
| password | 비밀번호 | X |
| type | 회원 유형 ( 구매자, 판매자, 관리자[스케줄러 포함] ) | ALL | 

`ALL` : 모든 유저 조회 가능
`X` : 조회 불가

**Comment by chhs2131** [comment]
이미 완료되었거나, 진행 예정이 없는 방치된 이슈를 `Closed` 상태로 두고 이슈를 종료합니다.
