### ISSUE TITLE
[FEATURE] 거래 내역은 경매 식별자, 구매(입찰) 가격, 구매 수량, 거래 유형(입찰, 환불), 구매자, 판매자, 생성일자를 포함한다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#111]
LastEdited: @chhs2131 

### ✨ Describe
- 선행 작업 #115 
- 거래 내역에 시간 관련 정보가 빠져 이를 보충합니다. 

### ✅ Todo

- BidHistoryInfo 수정
  - 거래 일자 DTO 추가
- BidHistory 수정
  - BidHistory에 CreatedAt 항목 추가
  - BaseTimeEntity 추가
- Test 추가
  - CreatedAt이 Null인 경우? 

### 🙋🏻 More
- 거래 입찰 시
  - CreatedAt이 현재 시간으로 생성된다.
  - UpdatedAt이 현재 시간으로 생성된다.
- 거래 환불 시
  - UpdatedAt이 현재 시간으로 갱신된다.
  - 거래 이력 상태가 `입찰`에서 `환불`로 변경된다.

**Comment by chhs2131** [comment]
거래내역 DTO에 생성일자 추가필요! 현재모습.
```java
public record BidHistoryInfo(
        long bidHistoryId,
        String productName,
        long price,
        long quantity,
        BidStatus bidStatus,
        long auctionId,
        Member seller,
        Member buyer
)
```
