### ISSUE TITLE
[FEATURE] 판매자는 경매 상품 목록 조회시 최대 100개의 상품을 조회할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#127]
### ✨ Describe
페이지네이션과 연관된 작업입니다. 하지만 최대 100개의 상품을 조회하는 제약만을 구현하면 해당 작업은 완료처리해주세요!

페이지네이션은 #130 에서 처리합니다.

### ✅ Todo
- [ ] 조회 목록이 101개일 때, 예외 처리 테스트 구현

**Comment by minseok-oh** [comment]
#204 <- 여기서 구현되었습니다
