### ISSUE TITLE
[FEATURE] 판매자는 경매의 가격 정책을 변경할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#143]
### ✨ Describe
- #12 과 중복된 요구사항이 있을 수 있습니다. 
- 코드 상 구현되었다면 PR 없이 Comment에 간단하게 어느 클래스 어느 메서드에 구현이 되었는지 명시하고 close 해주세요!

### ✅ Todo

**Comment by chhs2131** [comment]
이미 완료되었거나, 진행 예정이 없는 방치된 이슈를 `Closed` 상태로 두고 이슈를 종료합니다.
