### ISSUE TITLE
[FEATURE] 구매자 경매 상세 조회 SQL 작성 및 연동

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#150]
### ✨ Describe
- 경매 상세 조회기능을 위한 Persistence 구현체 메서드를 완성하고 테스트 코드를 작성합니다.
- 조회하는 데이터 셋은 다음 이슈 #47 를 참고해주세요.
### ✅ Todo
- [ ] 영속성 Repository 구현체 구현
- [ ] 영속성 조회 로직 테스트 작성

**Comment by minseok-oh** [comment]
#209 <- 여기서 작업했습니다
