### ISSUE TITLE
[FEATURE] 구매자 경매 목록 조회 SQL 작성 및 연동

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#152]
### ✨ Describe
- 사전 작업
  - #204

### ✅ Todo
- [x] 구매자 경매 목록 조회에 대한 Auction Service <-> Repository 연결
- [x] 해당 기능에 대한 테스트 작성 (AuctionCoreRepository)

### 🙋🏻 More
- 아래 이슈를 함께 처리합니다.
  - #239

**Comment by minseok-oh** [comment]
#204 <- 여기에서 구현되었습니다

**Comment by chhs2131** [comment]
Service <-> Repository 레이어간 연결은 안되어있어 다시 이슈를 활성시킵니다!
