### ISSUE TITLE
[TEST] 경매 환불 테스트에서 사용자 포인트를 영속 계층에 물어봐서 확인한다.

### ISSUE THREAD

**Issue by chhs2131** [woowa-techcamp-2024/Team7-ELEVEN#183]
### 🔨 Describe

> 메모리DB를 이용해서 테스트를 진행할 때, 테스트에 활용하던 Buyer와 Seller 객체가 그대로 메모리에 남아있어 테스트로는 확인이 안되던 문제였습니다. 
> 메모리 상에서는 포인트가 변경되었지만, 실제 영속적으로 반영되지는 않음

### 할일

**경매 환불 테스트 수정**
1. 경매 환불 테스트 시에 메모리DB를 활용하는 경우,  메모리에 있는 사용자 객체의 포인트가 수정된다.
2. 이를 영속적으로 저장하지 않는 경우, 실제 DB에는 해당 멤버의 포인트가 저장되어 있지 않게 된다.
3. 이는 실제 포인트 수정이 일어나지 않았음에도 마치 반영이 된 것처럼 보이게 해 테스트가 통과하는 문제가 생기게 된다.
메모리DB쓰면 어쩔 수 없는 문제인듯..

**PaymentServiceTest 간단 정리!**
- Nested로 분리...

### 🙋🏻 More

광복절 좋아!!

**Comment by HiiWee** [comment]
요 이슈에서 발생하는 문제는 지금도 유효한가요?

**Comment by chhs2131** [comment]
> 요 이슈에서 발생하는 문제는 지금도 유효한가요?

이제 H2 기반 테스트로 변경하면 괜찮을 듯 합니다~

**Comment by HiiWee** [comment]
H2 DB 업데이트 하면서 해결 완료~ 이슈 닫습니다!
