### ISSUE TITLE
[REFACTOR] `FakeRepository`를 `H2 Inmemory`를 적용한다

### ISSUE THREAD

**Issue by HiiWee** [woowa-techcamp-2024/Team7-ELEVEN#237]
### 🔨 Describe

- `JPA open in view` 설정 끄기
- `DatabaseCleaner`를 생성해서 모두 DB 초기화 작업을 진행한다.

**Comment by chhs2131** [comment]
해당 작업 진행시 아래 이슈도 함께 해결될 것 같습니다.
- #183
