### ISSUE TITLE
[STORY] 사용자 로그인 기능 로직 오류 수정

### ISSUE THREAD

**Issue by HiiWee** [woowa-techcamp-2024/Team7-ELEVEN#49]
### 🤔 사전작업

- #99

### ✨ 현재 진행하려는 작업
- [x] #54

### ➡️ 사후작업

- [x] #69
- [x] #64

**Comment by yudonggeun** [comment]
- #97 에서 중복해서 관리하고 있어서 프로젝트에서 제외합니다.
