### ISSUE TITLE
[STORY] 스케줄러는 경매의 가격을 수정할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#81]
경매는 시간과 전략에 따라서 외부에서 동적으로 수정을 해야합니다.

**Comment by chhs2131** [comment]
이미 완료되었거나, 진행 예정이 없는 방치된 이슈를 `Closed` 상태로 두고 이슈를 종료합니다.
