### ISSUE TITLE
[STORY] 판매자는 경매를 취소할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#95]
Author: @chhs2131 

## 🤔 사전작업
- 사용자는 판매자 권한으로 로그인되어 있어야 합니다.
- 판매자는 등록한 경매 품목이 하나 이상 있어야 합니다.
- 경매 상태 확인
  - 경매에게 현재 상태를 물어볼 수 있어야 한다. 

<br/>

### 작업 이슈
- [x] #154
- [x] #153
- [x] #171

### 참고자료
- **경매 삭제 기능 구현** (이건 고민이 됩니다!!)
  - 판매자가 보내는 경매 삭제 요청을 `AuctionManager`에서 구현한다.
  - 경매 삭제 요청 처리를 `AuctionService`에서 구현한다. 
- **검증 및 승인**
  - 삭제하려는 경매가 'WAITING' 상태인지 검증한다.
  - 경매를 생성한 판매자가 경매를 삭제하려는지 검증한다.
- **예외 처리**
  - 경매를 찾을 수 없는 경우에 대한 예외 처리를 구현합니다.
  - 경매를 생성하지 않은 판매자의 무단 액세스 시도에 대한 예외 처리를 구현합니다.
  - 유효하지 않은 경매 상태에 대한 예외 처리를 구현합니다
    - 예: 이미 시작되었거나 종료된 경매를 삭제하려고 시도
- **테스트**
  - 성공적인 삭제 케이스
  - 'WAITING' 상태가 아닌 경매 삭제 시도 케이스
  - 등등

![Image](https://github.com/user-attachments/assets/81d91378-2ab6-4ea8-acd3-0970e4abd7a7)

<br/>

## ➡️ 사후작업
- Soft Deletion으로 변경하기

**Comment by chhs2131** [comment]
아직 시작되지 않은 경매가 삭제되는 것이므로, '취소'라는 행위가 더 적합하다고 판단하여 수정하였습니다!
